version: "3.9"

services:
  server:
    build: ./server
    container_name: maftycv-server
    ports:
      - "5000:5000"
      - "5555:5555" # for prisma studio local
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/maftycv

  db:
    image: postgres:latest
    container_name: maftycv-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maftycv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
